const CONTROL_OVERLAY_DEFS = {
  "battery-toggle": {
    kind: "boolean",
    stateKey: "isBatteryOn",
    inflate: 1.0,
    offsetX: 22,
    offsetY: 5,
    z: 60,
    off: "./img/11/11_0001_Слой-2.png",
    on: "./img/11/11_0000_Слой-289-копия.png",
  },
  "gear-lever": {
    kind: "enum",
    stateKey: "gearLever",
    inflate: 1.2,
    offsetX: -12,
    offsetY: -25,
    z: 80,
    frames: {
      neutral: { src: "./img/1/1_0000s_0000_Слой-57-копия-8.png", offsetX: -10, offsetY: -25 },
      "1": { src: "./img/1/1_0000s_0001_Слой-57-копия-7.png", offsetX: -10, offsetY: -20 },
      "2": { src: "./img/1/1_0000s_0002_Слой-57-копия-6.png", offsetX: -10, offsetY: -14 },
      "3": { src: "./img/1/1_0000s_0003_Слой-57-копия-5.png", offsetX: -10, offsetY: -14 },
      "4": { src: "./img/1/1_0000s_0004_Слой-57-копия-4.png", offsetX: -8, offsetY: -8 },
      "5": { src: "./img/1/1_0000s_0005_Слой-57-копия-3.png", offsetX: -10, offsetY: -6 },
      R: { src: "./img/1/1_0000s_0006_Слой-57-копия-2.png", offsetX: -10, offsetY: -6 },
    },
  },
  shutters: {
    kind: "enum",
    stateKey: "shutters",
    inflate: 1.0,
    offsetX: -5,
    offsetY: 15,
    z: 55,
    frames: {
      false: "./img/2/2_0000s_0000_Слой-251-копия-2.png",
      partial: "./img/2/2_0000s_0001_Слой-251-копия.png",
      true: "./img/2/2_0000s_0002_Слой-251.png",
    },
  },
  "right-tank": {
    kind: "boolean",
    stateKey: "rightTank",
    inflate: 1.8,
    offsetX: 0,
    offsetY: 0,
    z: 79,
    off: "./img/3/3_0000_Группа-21-копия.png",
    on: "./img/3/3_0001_Группа-21.png",
  },
  "left-tank": {
    kind: "boolean",
    stateKey: "leftTank",
    inflate: 1.8,
    offsetX: 10,
    offsetY: 5,
    z: 55,
    off: "./img/4/4_0000_Группа-21-копия-3.png",
    on: "./img/4/4_0001_Группа-21-копия-2.png",
  },
  "gas-pedal": {
    kind: "boolean",
    stateKey: "gasPedal",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 18,
    z: 52,
    on: "./img/5/5_0000_Слой-317-копия.png",
    off: "./img/5/5_0001_Слой-2.png",
  },
  "brake-pedal": {
    kind: "boolean",
    stateKey: "brakeEffective",
    inflate: 1.8,
    offsetX: 0,
    offsetY: -60,
    z: 52,
    on: "./img/6/6-1.png",
    off: "./img/6/6-4.png",
  },
  "fuel-manual-feed": {
    kind: "range",
    stateKey: "fuelManualFeed",
    inflate: 2.6,
    offsetX: -34,
    offsetY: 80,
    z: 58,
    frames: [
      { at: 0, src: "./img/7/7_0000_Слой-306-копия-3.png", offsetX: -34, offsetY: 80 },
      { at: 33, src: "./img/7/7_0001_Слой-306-копия-2.png", offsetX: -38, offsetY: 60 },
      { at: 66, src: "./img/7/7_0002_Слой-306-копия.png", offsetX: -36, offsetY: 38 },
      { at: 100, src: "./img/7/7_0003_Слой-2.png", offsetX: -36, offsetY: 38 },
    ],
  },
  bcn: {
    kind: "enum",
    stateKey: "bcn",
    inflate: 1.4,
    offsetX: 0,
    offsetY: 0,
    z: 58,
    frames: {
      off: "./img/8/8_0003_Слой-2.png",
      on: "./img/8/8_0001_Слой-4.png",
      pump: "./img/8/8_0000_Слой-236-копия.png",
    },
  },
  "air-bleed-valve": {
    kind: "boolean",
    stateKey: "airBleedValve",
    inflate: 2.5,
    offsetX: 14,
    offsetY: 10,
    z: 58,
    on: "./img/9/9_0000_Слой-2.png",
    off: "./img/9/9_0001_Слой-314-копия.png",
  },
  "fuel-primer-lever": {
    kind: "boolean",
    stateKey: "fuelPrimerLever",
    inflate: 1.0,
    offsetX: -5,
    offsetY: 5,
    z: 58,
    off: "./img/10/10_0000_Слой-297-копия.png",
    on: "./img/10/10_0001_Слой-2.png",

  },

  azr: {
    kind: "enum",
    stateKey: "azr",
    inflate: 1.2,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    frames: {
      0: { src: "./img/12/12.png" },
      1: { src: "./img/12/12-1.png" },
      2: { src: "./img/12/12-2.png" },
    },
  },
  epk: {
    kind: "boolean",
    stateKey: "epk",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/zv1.png",
    on: "./img/12/zv2.png",
  },
  horn: {
    kind: "boolean",
    stateKey: "horn",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/zv1.png",
    on: "./img/12/zv2.png",
  },
  "mzn-engine": {
    kind: "boolean",
    stateKey: "mznEngine",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/zv1.png",
    on: "./img/12/zv2.png",
  },
  "ammeter-button": {
    kind: "boolean",
    stateKey: "ammeterButton",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/V-nazhat1.png",
    on: "./img/12/V-nazhat2.png",
  },

  "left-right-tanks": {
    kind: "enum",
    stateKey: "leftRightTanks",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    frames: {
      0: { src: "./img/12/Tmb2-r.png" },
      1: { src: "./img/12/Tmb3.png", inflate: 1.3 },
      2: { src: "./img/12/Tmb1-r.png" },
    },
  },
  "spark-plug": {
    kind: "enum",
    stateKey: "sparkPlug",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    frames: {
      0: { src: "./img/12/Tmb2-r.png" },
      1: { src: "./img/12/Tmb3.png", inflate: 1.3 },
      2: { src: "./img/12/Tmb1-r.png" },
    },
  },
  "engine-start": {
    kind: "enum",
    stateKey: "engineStart",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    frames: {
      0: { src: "./img/12/Tmb2-r.png" },
      1: { src: "./img/12/Tmb3.png", inflate: 1.3 },
      2: { src: "./img/12/Tmb1-r.png" },
    },
  },

  "emergency-hatch-rotation": {
    kind: "boolean",
    stateKey: "emergencyHatchRotation",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Kn1.png",
    on: "./img/12/Kn2.png",
  },
  "oil-pump-gearbox": {
    kind: "boolean",
    stateKey: "oilPumpGearbox",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Kn1.png",
    on: "./img/12/Kn2.png",
  },
  "commander-call": {
    kind: "boolean",
    stateKey: "commanderCall",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/лампа.png",
    on: "./img/12/лампа-актив.png",
  },
  "air-intake": {
    kind: "boolean",
    stateKey: "airIntake",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/лампа.png",
    on: "./img/12/лампа-актив.png",
  },

  // Remaining instrument panel toggles (tmb1/tmb2)
  heating: {
    kind: "boolean",
    stateKey: "heating",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  combined: {
    kind: "boolean",
    stateKey: "combined",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  "left-lights": {
    kind: "boolean",
    stateKey: "leftLights",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  "right-lights": {
    kind: "boolean",
    stateKey: "rightLights",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  "gabrate-lights": {
    kind: "boolean",
    stateKey: "gabrateLights",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  "lights-all": {
    kind: "boolean",
    stateKey: "lightsAll",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  "water-antifreeze": {
    kind: "boolean",
    stateKey: "waterAntifreeze",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  gpk: {
    kind: "boolean",
    stateKey: "gpk",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  "bca-tca": {
    kind: "boolean",
    stateKey: "bcaTca",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    off: "./img/12/Tmb1.png",
    on: "./img/12/Tmb2.png",
  },
  "mzn-tow": {
    kind: "enum",
    stateKey: "mznTow",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    frames: {
      0: { src: "./img/12/13-1.png" },
      1: { src: "./img/12/13-4.png" },
      2: { src: "./img/12/13-3.png" },
    },
  },
  starter: {
    kind: "enum",
    stateKey: "starter",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    frames: {
      0: { src: "./img/12/13-2.png" },
      1: { src: "./img/12/13-4.png" },
      2: { src: "./img/12/13-3.png" },
    },
  },
  "signal-lamps": {
    kind: "enum",
    stateKey: "signalLamps",
    inflate: 1.0,
    offsetX: 0,
    offsetY: 0,
    z: 70,
    frames: {
      0: { src: "./img/12/13.png" },
      1: { src: "./img/12/13-4.png" },
      2: { src: "./img/12/13-3.png" },
    },
  },
};

export { CONTROL_OVERLAY_DEFS };
